<script defer src="{{ mix('js/lazysize.js') }}"></script>
<script defer src="{{ mix('js/load-image-lazy.js') }}"></script>
<script src="{{ mix('js/jquery.min.js') }}"></script>
<script src="{{ mix('js/jquery-migrate-3.1.0.min.js') }}"></script>
<script src="{{ mix('js/popper.min.js') }}"></script>
<script src="{{ mix('js/bootstrap.min.js') }}"></script>
<script src="{{ mix('js/jquery.easing.js') }}"></script>
<script src="{{ mix('js/jquery.waypoints.min.js') }}"></script>
<script src="{{ mix('js/jquery.stellar.min.js') }}"></script>
<script src="{{ mix('js/owl.carousel.min.js') }}"></script>
<script src="{{ mix('js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ mix('js/aos.js') }}"></script>
<script src="{{ mix('js/jquery.animateNumber.min.js') }}"></script>
<script src="{{ mix('js/scrollax.min.js') }}"></script>
<script src="{{ mix('js/main.js') }}"></script>
<script defer src="{{ mix('js/captcha.js') }}"></script>
